### ISSUE TITLE
After tour is canceled/completed and started again, overlay is not present anymore

### ISSUE THREAD

**Issue by appleneil** [shipshapecode/react-shepherd#288]
Hey guys, I have the same issue as https://github.com/shipshapecode/shepherd/issues/347. The overlay is created on the first render but as soon as a tour is completed / cancelled the overlay is removed. If I start the tour again the overlay is not recreated.

**Comment by rwwagner90** [comment]
@chuckcarpenter this sounds like a potential regression from the work you did to destroy the overlays on cancel. Do we have tests making sure it gets created again when the tour is started again?

**Comment by chuckcarpenter** [comment]
fixed in Shepherd.js v7.1.1

**Comment by appleneil** [comment]
I've updated to 7.1.1 and the problem still persists

**Comment by rwwagner90** [comment]
Those `when` methods are for the step, not the tour. If you want to test when tour methods fire, please try `tour.on('cancel'` etc.

**Comment by appleneil** [comment]
> Those `when` methods are for the step, not the tour. If you want to test when tour methods fire, please try `tour.on('cancel'` etc.

ok, the tour events are logged correctly. The overlay still isn't created the second time round (whether the first tour was cancelled or completed) on `shepherdjs7.1.1` and `react-shepherd 3.1.0`

**Comment by rwwagner90** [comment]
@appleneil can you provide a reproduction?

**Comment by appleneil** [comment]
@rwwagner90 I recreated the problem in a fresh create-react-app using the following code
```javascript
{
  "name": "test-shepherd",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "react-shepherd": "^3.1.0",
    "shepherd.js": "^7.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

```javascript
import React, { Component, useContext } from 'react'
import './App.css'
import { ShepherdTour, ShepherdTourContext } from "react-shepherd"
import { steps as newSteps } from './steps'
import 'shepherd.js/dist/css/shepherd.css'

const tourOptions = {
  defaultStepOptions: {
    cancelIcon: {
      enabled: true
    }
  },
  useModalOverlay: true
};

function Button() {
  const tour = useContext(ShepherdTourContext);

  return (
    <button className="button dark" onClick={tour.start}>
      Start Tour
    </button>
  );
}

class App extends Component {
  render() {
    return (
      <div>
        <ShepherdTour steps={newSteps} tourOptions={tourOptions}>
          <Button/>
        </ShepherdTour>
      </div>
    );
  }
}

export default App
```

**Comment by rwwagner90** [comment]
Thanks @appleneil. @chuckcarpenter do you have time to take a look?

**Comment by chuckcarpenter** [comment]
@appleneil It is working for me, using this repo's test site in the `/example` folder. Can you tell me what you have when you `npm ls shepherd.js`? e.g., I have:

![image](https://user-images.githubusercontent.com/706378/79368294-02b16b80-7f04-11ea-86a3-47696d06d1d2.png)

**Comment by chuckcarpenter** [comment]
gif with working flows for both completion and cancel:

![out](https://user-images.githubusercontent.com/706378/79368374-21176700-7f04-11ea-8e91-72e485b2efad.gif)

**Comment by chuckcarpenter** [comment]
@appleneil I've updated the lock file in master to be explicit to 7.1.1, so try installing from there. I want to see if maybe you had version conflicts.

**Comment by appleneil** [comment]
> @appleneil It is working for me, using this repo's test site in the `/example` folder. Can you tell me what you have when you `npm ls shepherd.js`? e.g., I have:
> 
> ![image](https://user-images.githubusercontent.com/706378/79368294-02b16b80-7f04-11ea-86a3-47696d06d1d2.png)

@chuckcarpenter I've got 
<img width="218" alt="Screenshot 2020-04-16 at 08 04 41" src="https://user-images.githubusercontent.com/2428482/79420324-03580980-7fb9-11ea-9eac-c61c53bf18b0.png">

**Comment by appleneil** [comment]
@chuckcarpenter even in the example code I've got
![image](https://user-images.githubusercontent.com/2428482/79424269-2e922700-7fc0-11ea-8459-3c924e117adc.png)
and the problem still persists... :-(

**Comment by rwwagner90** [comment]
I'm also unable to reproduce this. @appleneil can you please make a codepen or similar to show the error? Since we are not able to reproduce, there is no way for us to debug. Also, what browser are you using?

**Comment by chuckcarpenter** [comment]
@appleneil your screenshot shows you have the version with the bug
![](https://user-images.githubusercontent.com/2428482/79420324-03580980-7fb9-11ea-9eac-c61c53bf18b0.png)

You need to be using v7.1.1 for it to work

**Comment by appleneil** [comment]
@rwwagner90 I'm unable to give you guys a codepen, I can't get react-shepherd on there.
@chuckcarpenter I've restarted my project making sure that I had v7.1.1 and double checked my simple create-react-app and I still have the problem. I'm using Chrome 81. 
I even have the problem with your example 
![image](https://user-images.githubusercontent.com/2428482/79473533-8c952d80-8005-11ea-8b6f-01bfbf08ad34.png)
I'm on node v10.17.0, npm v6.11.3

**Comment by rwwagner90** [comment]
@appleneil you can add scripts to codepen in settings. You can use something like https://cdn.jsdelivr.net/npm/shepherd.js@7.1.1/dist/css/shepherd.css except change the paths to be for react-Shepherd.

**Comment by appleneil** [comment]
> @appleneil you can add scripts to codepen in settings. You can use something like https://cdn.jsdelivr.net/npm/shepherd.js@7.1.1/dist/css/shepherd.css except change the paths to be for react-Shepherd.

I'm trying to get one sorted, but I keep getting errors whenever I try to use either `const tour = useContext(ShepherdTourContext);` or the `<ShepherdTour>`. The error thrown is https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]=

**Comment by chuckcarpenter** [comment]
@appleneil I have a working sandbox here: https://codesandbox.io/s/admiring-hellman-23nzm

Loading from a CDN will only have the last published version. I'm going to try to update this to use the new lock file and perhaps save you time in an example. Feel free to fork mine and see if you have things causing issues still.

**Comment by appleneil** [comment]
@chuckcarpenter I'll give it a try from your sandbox. Thanks guys for all your help

**Comment by appleneil** [comment]
@chuckcarpenter @rwwagner90 just to let you know, that did the trick, and everything works great. Thanks again
